"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { 
  Eye, 
  Download, 
  Search, 
  Printer, 
  FileText, 
  User, 
  Calendar, 
  ShieldCheck, 
  Filter,
  CheckCircle2,
  Mail,
  Copy
} from "lucide-react";
import { getReceipts } from "@/lib/api";
import { Receipt } from "@/lib/types";
import { Skeleton } from "@/components/ui/skeleton";
import { downloadReceipt } from "@/lib/pdf";
import { toast } from "sonner";
import { cn } from "@/lib/utils";



// Reusable Receipt Content Component
function ReceiptContent({ receipt, id, className }: { receipt: Receipt; id?: string; className?: string }) {
  return (
    <div id={id} className={cn("animate-in fade-in zoom-in-95 duration-300 bg-white", className)}>
      <div className="bg-slate-900 p-8 text-white flex justify-between items-start">
        <div>
          <h2 className="text-xs font-black uppercase tracking-[0.2em] text-slate-400 mb-1">Fee Receipt</h2>
          <p className="text-2xl font-bold italic">SmartFee Pro</p>
        </div>
        <div className="text-right">
          <p className="text-xs font-bold text-slate-400 uppercase">Receipt No.</p>
          <p className="text-lg font-mono font-bold text-emerald-400">{receipt.receiptNumber}</p>
        </div>
      </div>

      <div className="p-8 space-y-8 bg-white">
        <div className="grid grid-cols-2 gap-8">
          <div className="space-y-1">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Student Name</p>
            <p className="font-bold text-slate-900">{receipt.studentName}</p>
            <p className="text-xs text-indigo-600 font-bold uppercase tracking-tight">{receipt.course || 'N/A'} {receipt.academicYear && `| ${receipt.academicYear}`}</p>
          </div>
          <div className="space-y-1 text-right">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Transaction Date</p>
            <p className="font-bold text-slate-900">{new Date(receipt.paymentDate).toLocaleDateString(undefined, { dateStyle: 'full' })}</p>
          </div>
        </div>

        <div className="border-y border-slate-100 py-6 grid grid-cols-3 gap-8">
          <div className="space-y-1">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Channel</p>
            <p className="text-sm font-bold text-slate-700 uppercase">{receipt.paymentMethod.replace("_", " ")}</p>
          </div>
          <div className="space-y-1">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Target Session</p>
            <p className="text-sm font-bold text-slate-700 uppercase">{receipt.month}</p>
          </div>
          <div className="space-y-1 text-right">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Reference No.</p>
            <p className="text-sm font-mono font-bold text-slate-700">{receipt.utrId}</p>
          </div>
        </div>

        <div className="flex justify-between items-center bg-slate-50 rounded-2xl p-6 border border-slate-100">
          <div>
            <p className="text-xs font-bold text-slate-500 uppercase">Payment Status</p>
            <div className="flex items-center gap-2 text-emerald-600 font-black text-lg">
              <CheckCircle2 className="w-5 h-5" />
              CLEARED
            </div>
          </div>
          <div className="text-right">
            <p className="text-xs font-bold text-slate-500">Net Amount Paid</p>
            <p className="text-3xl font-black text-slate-900">₹{receipt.amount.toLocaleString()}</p>
          </div>
        </div>

        <div className="pt-8 text-center border-t border-slate-50">
          <p className="text-[9px] text-slate-400 font-bold uppercase tracking-widest leading-relaxed">
            SmartFee University Pro • Academic Financial Services • Contact: support@smartfee.pro<br/>
            This is a legally valid digital instrument generated by SmartFee University ERP.
          </p>
        </div>
      </div>
    </div>
  );
}

export default function ReceiptsPage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [receipts, setReceipts] = useState<Receipt[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedReceipt, setSelectedReceipt] = useState<Receipt | null>(null);

  useEffect(() => {
    let mounted = true;
    const load = async () => {
      try {
        setIsLoading(true);
        const data = await getReceipts();
        if (mounted) {
          setReceipts(data);
        }
      } catch (err) {
        if (mounted) {
          console.error("Error fetching receipts:", err);
          setError("Failed to load receipts");
        }
      } finally {
        if (mounted) {
          setIsLoading(false);
        }
      }
    };
    load();
    return () => {
      mounted = false;
    };
  }, []);

  const filteredReceipts = receipts.filter(
    (receipt) =>
      (receipt.studentName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      receipt.receiptNumber?.toLowerCase().includes(searchTerm.toLowerCase())) ?? false
  );

  const handleDownload = async (receipt: Receipt) => {
    try {
      setSelectedReceipt(receipt);
      toast.loading("Preparing digital receipt...", { id: "pdf-gen" });
      
      // Short delay for the hidden container to render with the new receipt
      setTimeout(async () => {
        try {
          await downloadReceipt("download-capture-area", `Receipt_${receipt.receiptNumber}`);
          toast.success("Receipt saved successfully", { id: "pdf-gen" });
        } catch (err) {
          console.error(err);
          toast.error("Generation failed. Try Print as PDF.", { id: "pdf-gen" });
        }
      }, 500);
    } catch (err) {
      toast.error("Failed to initialize download", { id: "pdf-gen" });
    }
  };

  const handleCopyUtr = (utr: string) => {
    navigator.clipboard.writeText(utr);
    toast.success("UTR ID copied to clipboard");
  };

  if (error) {
    return (
      <div className="p-8">
        <Card className="p-8 border-red-200 bg-red-50 flex flex-col items-center">
          <FileText className="w-12 h-12 text-red-500 mb-4" />
          <h2 className="text-xl font-bold text-red-900 mb-2">Error Loading Receipts</h2>
          <p className="text-red-700 mb-6">{error}</p>
          <Button onClick={() => window.location.reload()} variant="outline">
            Retry
          </Button>
        </Card>
      </div>
    );
  }

  return (
    <div className="p-4 md:p-8 space-y-8 bg-slate-50/30 min-h-screen">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 no-print">
        <div>
          <h1 className="text-3xl font-black tracking-tight text-slate-900 uppercase">Receipt Ledger</h1>
          <p className="text-slate-500 mt-1">
            Access and manage digital payment certificates for all fee transactions.
          </p>
        </div>
      </div>

      {/* Search & Filter Bar */}
      <Card className="rounded-2xl border-none shadow-sm bg-white overflow-hidden no-print">
        <CardContent className="p-4 md:p-6 flex flex-col md:flex-row gap-4 items-center">
          <div className="relative flex-1 group w-full">
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 group-focus-within:text-indigo-500 transition-colors" />
            <Input
              placeholder="Search by student name or receipt number..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 h-11 bg-slate-50 border-transparent rounded-xl focus:bg-white focus:border-indigo-100 focus:ring-4 focus:ring-indigo-50 transition-all text-sm w-full"
            />
          </div>
          <Button variant="ghost" className="rounded-xl px-6 text-slate-500 hover:text-indigo-600">
            <Filter className="w-4 h-4 mr-2" />
            Advanced
          </Button>
        </CardContent>
      </Card>

      {/* Grid of Receipts */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 no-print">
        {isLoading ? (
          Array.from({ length: 6 }).map((_, i) => (
            <Card key={i} className="rounded-2xl border-none shadow-sm h-[280px]">
              <CardContent className="p-6 space-y-4">
                <Skeleton className="h-6 w-32 rounded-lg" />
                <Skeleton className="h-10 w-full rounded-lg" />
                <Skeleton className="h-12 w-full rounded-lg" />
                <div className="pt-4 flex gap-2">
                  <Skeleton className="h-10 flex-1 rounded-xl" />
                  <Skeleton className="h-10 flex-1 rounded-xl" />
                </div>
              </CardContent>
            </Card>
          ))
        ) : filteredReceipts.length > 0 ? (
          filteredReceipts.map((receipt) => (
            <Card
              key={receipt.id}
              className="rounded-2xl border-none shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all bg-white group overflow-hidden"
            >
              <div className="bg-slate-900 h-1.5 w-full" />
              <CardContent className="p-6 space-y-5">
                <div className="flex justify-between items-start">
                  <div className="space-y-0.5">
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Certificate No.</p>
                    <p className="text-sm font-mono font-bold text-slate-900">{receipt.receiptNumber}</p>
                  </div>
                  <Badge className="bg-emerald-50 text-emerald-600 border-0 text-[10px] font-black px-2 py-0.5 uppercase">
                    Verified
                  </Badge>
                </div>

                <div className="space-y-1">
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Student</p>
                  <div className="flex flex-col">
                    <span className="font-bold text-slate-900 text-sm">{receipt.studentName}</span>
                    <span className="text-[10px] text-slate-400">{receipt.course}</span>
                  </div>
                </div>

                <div className="flex justify-between items-end bg-slate-50 rounded-xl p-3 border border-slate-100">
                  <div>
                    <p className="text-[10px] font-bold text-slate-500 uppercase">Collection</p>
                    <p className="text-lg font-black text-slate-900">₹{receipt.amount.toLocaleString()}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-[10px] font-bold text-slate-500 uppercase">Academic Session</p>
                    <p className="text-xs font-bold text-indigo-600">{receipt.month}</p>
                  </div>
                </div>

                <div className="flex justify-between text-[10px] font-bold text-slate-400 uppercase tracking-tight">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    {new Date(receipt.paymentDate).toLocaleDateString()}
                  </span>
                  <span className="flex items-center gap-1 group/utr cursor-pointer hover:text-slate-900" onClick={() => handleCopyUtr(receipt.utrId)}>
                    <ShieldCheck className="w-3 h-3" />
                    UTR: {receipt.utrId.slice(0, 8)}...
                    <Copy className="w-2.5 h-2.5 ml-1 opacity-0 group-hover/utr:opacity-100 transition-opacity" />
                  </span>
                </div>

                <div className="flex gap-2 pt-2">
                  <Dialog onOpenChange={(open) => { if(open) setSelectedReceipt(receipt); }}>
                    <DialogTrigger asChild>
                      <Button
                        variant="outline"
                        size="sm"
                        className="flex-1 rounded-xl border-slate-200 font-bold text-xs h-10 hover:bg-slate-50"
                      >
                        <Eye className="w-3.5 h-3.5 mr-2" />
                        Preview
                      </Button>
                    </DialogTrigger>
                    <DialogContent className="sm:max-w-[650px] rounded-3xl border-none shadow-2xl p-0 overflow-hidden">
                      <DialogHeader className="sr-only">
                        <DialogTitle>Receipt Preview - {selectedReceipt?.receiptNumber}</DialogTitle>
                        <DialogDescription>Detailed view of the payment receipt</DialogDescription>
                      </DialogHeader>
                      {selectedReceipt && (
                        <div className="bg-white">
                          <ReceiptContent receipt={selectedReceipt} />
                          <div className="p-8 pt-0 flex gap-3 justify-end no-print">

                            <Button
                              variant="outline"
                              className="rounded-xl border-slate-200"
                              onClick={() => window.print()}
                            >
                              <Printer className="w-4 h-4 mr-2" />
                              Print
                            </Button>
                            <Button 
                              className="rounded-xl bg-slate-900 hover:bg-slate-800 h-10 px-8"
                              onClick={() => handleDownload(selectedReceipt)}
                            >
                              <Download className="w-4 h-4 mr-2" />
                              Download PDF
                            </Button>
                          </div>
                        </div>
                      )}
                    </DialogContent>
                  </Dialog>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="flex-1 rounded-xl text-indigo-600 hover:text-indigo-700 hover:bg-indigo-50 font-bold text-xs h-10"
                    onClick={() => handleDownload(receipt)}
                  >
                    <Download className="w-3.5 h-3.5 mr-2" />
                    Download
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))
        ) : (
          <div className="col-span-full py-20 text-center">
            <div className="bg-slate-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 text-slate-400">
              <FileText className="w-8 h-8" />
            </div>
            <h3 className="text-lg font-bold text-slate-900">No matching records</h3>
            <Button variant="link" className="mt-4 text-indigo-600" onClick={() => setSearchTerm("")}>
              Clear Search
            </Button>
          </div>
        )}
      </div>

      {/* Hidden container for PDF capture (Off-screen but in DOM) */}
      <div className="fixed -left-[4000px] top-0 pointer-events-none opacity-0">
        {selectedReceipt && (
          <div id="download-capture-area" className="w-[1000px] bg-white">
             <ReceiptContent receipt={selectedReceipt} />
          </div>
        )}
      </div>
    </div>
  );
}
